version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/fixtures/art"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/attribute-behavior"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/concurrent"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/devtools"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/dom"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/eslint"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/expiration"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/fiber-debugger"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/fizz"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/fizz-ssr-browser"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/flight"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/flight-esm"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/legacy-jsx-runtimes"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/nesting"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/packaging"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/scheduler"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/ssr"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/ssr-2"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/fixtures/stacks"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
