version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "hello John"


workflows:

  test:
    when:
      matches:
        pattern: "^replay.*"
        value: << pipeline.git.branch >>
    jobs:
      - test