name: Commit Artifacts for Facebook WWW

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Build from source
        run: |
          yarn install --frozen-lockfile && yarn build-combined
      - name: Strip @license from eslint plugin and react-refresh
        run: |
          sed -i -e 's/ @license React*//' \
            build/oss-stable/eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.development.js \
            build/oss-stable/react-refresh/cjs/react-refresh-babel.development.js
      - name: Move relevant files into compiled
        run: |
          mkdir -p ./compiled
          mkdir -p ./compiled/facebook-www
          mkdir -p ./compiled/babel-plugin-react-refresh

          # Copy the facebook-www folder into compiled
          mv build/facebook-www ./compiled

          # Copy WARNINGS to facebook-www
          mv build/WARNINGS ./compiled/facebook-www/WARNINGS

          # Copy eslint-plugin-react-hooks into facebook-www
          mv build/oss-stable/eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.development.js \
            ./compiled/facebook-www/eslint-plugin-react-hooks.js

          # Copy unstable_server-external-runtime.js into facebook-www
          mv build/oss-stable/react-dom/unstable_server-external-runtime.js \
            ./compiled/facebook-www/unstable_server-external-runtime.js

          # Copy react-refresh-babel.development.js into babel-plugin-react-refresh
          mv build/oss-stable/react-refresh/cjs/react-refresh-babel.development.js \
            ./compiled/babel-plugin-react-refresh/index.js

          ls -R ./compiled
      - name: Add REVISION files
        run: |
          echo ${{ github.sha }} >> ./compiled/facebook-www/REVISION
          cp ./compiled/facebook-www/REVISION ./compiled/facebook-www/REVISION_TRANSFORMS
      - uses: actions/upload-artifact@v3
        with:
          name: compiled
          path: compiled/

  commit_artifacts:
    needs: build_artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: builds/facebook-www-temp
      - name: Ensure clean directory
        run: rm -rf compiled
      - uses: actions/download-artifact@v3
        with:
          name: compiled
          path: compiled/
      - run: git status -u
      - name: Commit changes to branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |
            ${{ github.event.head_commit.message }}

            DiffTrain build for [${{ github.sha }}](https://github.com/facebook/react/commit/${{ github.sha }})
            [View git log for this commit](https://github.com/facebook/react/commits/${{ github.sha }})
          branch: builds/facebook-www
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@users.noreply.github.com
          create_branch: true
